export const SET_TRANSACTION_LOADING = "SET_TRANSACTION_LOADING";
export const SET_TRANSACTION_ERROR = "SET_TRANSACTION_ERROR";
export const SET_HISTORY = "SET_HISTORY";
export const SET_HISTORY_LOADING = "SET_HISTORY_LOADING";
export const SET_HISTORY_ERROR = "SET_HISTORY_ERROR";
