export const SET_CARDS_LOADING = "SET_CARDS_LOADING";
export const SET_CARDS_ERROR = "SET_CARDS_ERROR";
export const SET_CARDS = "SET_CARDS";
export const REMOVE_CARD_LOADING = "REMOVE_CARD_LOADING";
export const REMOVE_CARD_ERROR = "REMOVE_CARD_ERROR";
export const SET_CARD_HISTORY = "SET_CARD_HISTORY";
export const CARD_HISTORY_LOADING = "CARD_HISTORY_LOADING";
export const CARD_HISTORY_ERROR = "CARD_HISTORY_ERROR";
